import type {
  FeishuInteractiveCard,
  MonitoringIncSummaryData,
} from '../../communication.types';

export class FeishuCardService {
  /**
   * Menghasilkan Interactive Card Feishu untuk Laporan Monitoring INC sesuai spesifikasi LTMS.
   */
  public generateMonitoringIncCard(
    data: MonitoringIncSummaryData,
    imageKey?: string
  ): FeishuInteractiveCard {
    const formattedTotal = Number(data.total || 0).toLocaleString('id-ID');
    const formattedBelum = Number(data.belum || 0).toLocaleString('id-ID');
    const formattedLate = Number(data.late || 0).toLocaleString('id-ID');
    const percent = Math.round(Number(data.percent || 0));

    // Top Kecamatan list formatting
    const topKecList = (data.topKecamatan && data.topKecamatan.length > 0)
      ? data.topKecamatan.map((k) => `• ${k}`).join('\n')
      : '• Sesuai data terlampir';

    const timeStr = data.generateTime || new Intl.DateTimeFormat('id-ID', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    }).format(new Date());

    const elements: any[] = [
      // 1. Header Information (Target Kota & Timestamp)
      {
        tag: 'div',
        fields: [
          {
            is_short: true,
            text: {
              tag: 'lark_md',
              content: `**Target Kota:**\n📍 **${data.targetKota.toUpperCase()}**`,
            },
          },
          {
            is_short: true,
            text: {
              tag: 'lark_md',
              content: `**Waktu Generate:**\n🕒 ${timeStr}`,
            },
          },
        ],
      },
      {
        tag: 'hr',
      },
      // 2. Summary KPI Metrics Grid
      {
        tag: 'div',
        fields: [
          {
            is_short: true,
            text: {
              tag: 'lark_md',
              content: `**📦 Total Resi:**\n**${formattedTotal}**`,
            },
          },
          {
            is_short: true,
            text: {
              tag: 'lark_md',
              content: `**⏳ Belum TTD:**\n**${formattedBelum}**`,
            },
          },
          {
            is_short: true,
            text: {
              tag: 'lark_md',
              content: `**🚨 Lewat SLA:**\n<font color='red'>**${formattedLate}**</font>`,
            },
          },
          {
            is_short: true,
            text: {
              tag: 'lark_md',
              content: `**📈 Progress:**\n<font color='green'>**${percent}%**</font>`,
            },
          },
        ],
      },
      {
        tag: 'hr',
      },
      // 3. Top Kecamatan
      {
        tag: 'div',
        text: {
          tag: 'lark_md',
          content: `**🏙️ Top Kecamatan:**\n${topKecList}`,
        },
      },
      // 4. Instructions Note
      {
        tag: 'note',
        elements: [
          {
            tag: 'plain_text',
            content:
              'Mohon segera dilakukan tindak lanjut terhadap seluruh paket yang masih belum TTD, khususnya paket yang telah melewati SLA.',
          },
        ],
      },
    ];

    // 5. Lampiran Gambar jika imageKey tersedia
    if (imageKey) {
      elements.push({
        tag: 'img',
        img_key: imageKey,
        alt: {
          tag: 'plain_text',
          content: `Monitoring INC ${data.targetKota}`,
        },
        mode: 'fit_horizontal',
      });
    }

    // 6. Footer Note
    elements.push(
      {
        tag: 'hr',
      },
      {
        tag: 'note',
        elements: [
          {
            tag: 'plain_text',
            content: `Generated by LTMS • ${new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })} WIB`,
          },
        ],
      }
    );

    return {
      config: {
        wide_screen_mode: true,
        enable_forward: true,
      },
      header: {
        title: {
          tag: 'plain_text',
          content: `LTMS • Monitoring INC ${data.targetKota}`,
        },
        template: 'red',
      },
      elements,
    };
  }
}

export const feishuCardService = new FeishuCardService();
